# Generated by Django 5.1.2 on 2024-10-22 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=100)),
                ('docente_asignatura', models.CharField(max_length=60)),
                ('progr_academico', models.CharField(max_length=100)),
                ('num_creditos', models.IntegerField()),
                ('duracion_en_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula_o_Laboratorio',
            fields=[
                ('id_aula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('piso', models.IntegerField()),
                ('num_proyector', models.IntegerField()),
                ('televisor', models.BooleanField()),
                ('capacidad_Estudiantes', models.IntegerField()),
                ('num_equipos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.asignatura')),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.aula_o_laboratorio')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.horario')),
            ],
        ),
    ]
