# Generated by Django 5.1.2 on 2024-10-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0002_asignatura_horario_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_y_materia',
            fields=[
                ('id_horario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('grupo', models.CharField(max_length=20)),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.horario_y_materia'),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
