# Generated by Django 5.1.2 on 2024-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0003_horario_y_materia_alter_asignacion_id_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_y_materia',
            name='num_estudiantes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
