# Generated by Django 5.1.2 on 2024-10-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0004_horario_y_materia_num_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='id_asignacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
