# Generated by Django 5.1.2 on 2024-10-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0005_alter_asignacion_id_asignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario_y_materia',
            old_name='id_horario',
            new_name='id_materia',
        ),
    ]
