# Generated by Django 5.1.2 on 2024-10-31 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0006_rename_id_horario_horario_y_materia_id_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='id_horario',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='nombre_asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.horario_y_materia'),
        ),
    ]
