# Generated by Django 5.1.2 on 2024-10-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0007_remove_asignacion_id_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='docente_asignatura',
        ),
    ]
