# Generated by Django 5.1.2 on 2024-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0008_remove_asignatura_docente_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='docente_asignatura',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
