# Generated by Django 5.1.2 on 2024-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0009_asignacion_docente_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=100)),
            ],
        ),
    ]
