# Generated by Django 5.1.2 on 2024-11-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0011_alter_asignatura_id_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_y_materia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.asignatura'),
        ),
    ]
