# Generated by Django 5.1.2 on 2024-11-05 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0013_remove_asignatura_horario_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='docente_asignatura',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Asignaciones.docentes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='duracion_en_horas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='num_creditos',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
