# Generated by Django 5.1.2 on 2024-11-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0014_remove_asignacion_docente_asignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario_y_materia',
            name='docente',
        ),
    ]
