# Generated by Django 5.1.2 on 2024-11-05 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0015_remove_horario_y_materia_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_y_materia',
            name='dia',
            field=models.CharField(choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miercoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='horario_y_materia',
            name='num_estudiantes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
