# Generated by Django 5.1.2 on 2024-11-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0016_alter_horario_y_materia_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.CharField(default='segundo', max_length=100),
            preserve_default=False,
        ),
    ]
