# Generated by Django 5.1.5 on 2025-03-16 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0019_disponibilidaddocente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='nombre_asignatura',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='horario_y_materia',
            name='id_materia',
        ),
        migrations.AddField(
            model_name='horario_y_materia',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horario_y_materia',
            name='dia',
            field=models.CharField(blank=True, choices=[('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miércoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='horario_y_materia',
            name='grupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario_y_materia',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario_y_materia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario_y_materia',
            name='num_estudiantes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
