# Generated by Django 5.1.5 on 2025-03-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0020_rename_nombre_asignatura_asignacion_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='horario',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='nombre_asignatura',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Asignaciones.horario_y_materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Asignaciones.aula_o_laboratorio'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='id_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Asignaciones.docentes'),
        ),
    ]
